import { SesiPenilaian } from "../types";

export function getSampleSession(): SesiPenilaian {
  return {
    id: `sesi-contoh-${Date.now()}`,
    namaSiswa: "Dimas Arya Pratama",
    nomorInduk: "202410782",
    kelas: "XII MIPA 3",
    mataPelajaran: "Biologi & Bahasa Indonesia",
    judulUjian: "Penilaian Harian: Sintesis Protein & Analisis Argumentasi",
    tanggal: new Date().toISOString().split("T")[0],
    catatanGuru: "Siswa memiliki pemahaman konsep biologi yang baik, namun pada soal nomor 2 terdapat indikasi penggunaan generator teks AI.",
    totalNilaiDiberikan: 34.5,
    totalNilaiMaksimal: 40,
    nilaiSkala100: 86.3,
    rataRataKesesuaianPersen: 90,
    rataRataAiPersen: 38,
    rataRataPlagiarismePersen: 15,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    soalList: [
      {
        id: "soal-contoh-1",
        nomorSoal: 1,
        nilaiMaksimal: 20,
        naskahSoal: "Jelaskan tahapan transkripsi dan translasi pada sintesis protein dalam sel eukariotik! Sebutkan di mana masing-masing proses tersebut berlangsung.",
        jawabanTeks: "Transkripsi terjadi di dalam nukleus (inti sel), di mana rantai DNA dicetak menjadi mRNA oleh enzim RNA polimerase. Setelah mRNA matang, ia keluar dari inti sel menuju sitoplasma. Selanjutnya tahap translasi berlangsung di ribosom, di mana mRNA dibaca kodon per kodon oleh tRNA yang membawa asam amino sesuai untuk dirangkai menjadi rantai polipeptida atau protein.",
        isSaved: true,
        analisis: {
          soalId: "soal-contoh-1",
          nomorSoal: 1,
          kesesuaianPersen: 95,
          indikasiAiPersen: 12,
          indikasiPlagiarismePersen: 10,
          plagiarismeKategori: "Sangat Rendah (Bebas Plagiat)",
          nilaiDiberikan: 19,
          nilaiMaksimal: 20,
          aiDugaanKategori: "Sangat Rendah (Asli Siswa)",
          ringkasanAnalisis: "Jawaban sangat tepat, runtut, dan menjelaskan lokasi serta mekanisme transkripsi maupun translasi dengan bahasa yang natural khas siswa.",
          ciriCiriAiTerdeteksi: ["Gaya penuturan ringkas dan langsung to-the-point", "Struktur kalimat organik tanpa pengulangan formal"],
          kelebihanJawaban: ["Menyebutkan enzim RNA polimerase secara tepat", "Menjelaskan perpindahan mRNA dari nukleus ke sitoplasma/ribosom"],
          kelemahanJawaban: ["Dapat ditambahkan penjelasan mengenai tahap inisiasi, elongasi, dan terminasi"],
          rekomendasiGuru: "Apresiasi penguasaan konsep siswa yang sangat matang pada bab genetika.",
          analyzedAt: new Date().toISOString(),
        },
      },
      {
        id: "soal-contoh-2",
        nomorSoal: 2,
        nilaiMaksimal: 20,
        naskahSoal: "Mengapa etika kecerdasan buatan (AI Ethics) penting diajarkan kepada generasi muda di era transformasi digital? Berikan analisis argumentatif Anda!",
        jawabanTeks: "Tentu, berikut adalah beberapa alasan mengapa etika AI sangat penting: Pertama, dalam lanskap digital yang kian dinamis, generasi muda berinteraksi langsung dengan algoritma cerdas yang memengaruhi pengambilan keputusan. Kedua, mitigasi bias algoritma dan perlindungan privasi data pribadi menjadi urgensi moral guna memastikan keadilan sosial. Ketiga, pemahaman etika menumbuhkan tanggung jawab digital holistik demi kemaslahatan masa depan peradaban manusia.",
        isSaved: true,
        analisis: {
          soalId: "soal-contoh-2",
          nomorSoal: 2,
          kesesuaianPersen: 85,
          indikasiAiPersen: 64,
          indikasiPlagiarismePersen: 20,
          plagiarismeKategori: "Rendah (Sedikit Kesamaan Sumber Umum)",
          nilaiDiberikan: 15.5,
          nilaiMaksimal: 20,
          aiDugaanKategori: "Tinggi (Didominasi AI)",
          ringkasanAnalisis: "Secara materiil argumen relevan dan padat, namun struktur pembuka ('Tentu, berikut adalah...'), diksi hiperbolik ('lanskap digital yang kian dinamis', 'peradaban manusia'), serta format poin simetris menunjukkan kemungkinan tinggi pemanfaatan AI generative.",
          ciriCiriAiTerdeteksi: ["Pembuka klise 'Tentu, berikut adalah...'", "Frasa formal berlebihan khas mesin penerjemah/LLM", "Pola enumerasi simetris kaku"],
          kelebihanJawaban: ["Mencakup poin privasi data, bias algoritma, dan tanggung jawab sosial"],
          kelemahanJawaban: ["Kurang mencerminkan opini personal atau studi kasus kontekstual siswa di lingkungan sekolah"],
          rekomendasiGuru: "Ajak siswa berdiskusi secara lisan mengenai poin-poin yang ditulisnya untuk memverifikasi pemahaman orisinalnya.",
          analyzedAt: new Date().toISOString(),
        },
      },
    ],
  };
}
